### ISSUE TITLE
Maskar's Map Features Suggestion List

### ISSUE THREAD

**Issue by PlannedExponent** [SWRP-GitHub/SWRP-Website#11]
- Feedback-Based Interactivity; this looks cool, but it also means people have more of a solid sense of what they're selecting and searching for. 
- Post Location System; some kind of information in regional or planetary popups showing you the location of posts within the galaxy would be very cool to see.
- Dynamic Border History; the ability to see the changes in faction borders over time would be interesting, though I have no idea how feasible this is.
- Region Specific Maps; the ability to focus on specific regions of the galaxy and have the rest of the map fade from view, become transparent, etc, etc, would be nice to see.
- Dynamic Map Modes; the ability to see regions of high player activity based on the number of posts, areas where certain factions tend to post, etc, etc; really just any sort of interesting informational overlays; would be cool.

**Comment by SWRP-GitHub** [comment]
Thanks for the feedback, ill start looking into these as some of them seem more then doable as we fill in the map with planet/region data.

Ill dm you for more info if needed
